/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import conexaobd.DAO.IntegranteDAO;
import conexaobd.DAO.JogadorDAO;
import conexaobd.DAO.PatrocinioDAO;
import conexaobd.DAO.TimeDAO;
import conexaobd.DAO.TreinadorDAO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author Fernando
 */
public class TelaInicial extends javax.swing.JFrame {
    Time t1 = new Time();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ctop = new javax.swing.JTextField();
        Cselva = new javax.swing.JTextField();
        Cmid = new javax.swing.JTextField();
        Cadc = new javax.swing.JTextField();
        Csup = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Ctreinador = new javax.swing.JTextField();
        Cidade = new javax.swing.JTextField();
        Ctitulos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cnometime = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Cpatrocinador1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Cinvestimento1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Cpatrocinador2 = new javax.swing.JTextField();
        Cinvestimento2 = new javax.swing.JTextField();

        jLabel7.setText("Nome do Time:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastre seu Time"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogadores"));

        jLabel1.setText("Insira o Nick dos jogadores de cada rota:");

        jLabel2.setText("Topo");

        jLabel3.setText("Selva");

        jLabel4.setText("Meio");

        jLabel5.setText("Atirador");

        jLabel6.setText("Suporte");

        Ctop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Csup))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ctop)
                            .addComponent(Cselva)
                            .addComponent(Cmid)
                            .addComponent(Cadc))))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Ctop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cselva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Cadc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Csup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Treinador"));

        jLabel9.setText("Nick:");

        jLabel10.setText("Idade:");

        jLabel11.setText("Títulos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(Ctitulos))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Ctreinador))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Ctreinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Ctitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Nome do Time:");

        Cnometime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnometimeActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel12.setText("Patrocinador 1:");

        jLabel13.setText("Investimento 1:");

        jLabel14.setText("Patrocinador 2:");

        jLabel15.setText("Investimento 2:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnCadastrar)
                        .addGap(49, 49, 49)
                        .addComponent(btnIniciar)
                        .addGap(101, 101, 101))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cnometime, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Cinvestimento1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(Cpatrocinador1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Cpatrocinador2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(Cinvestimento2))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Cnometime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Cpatrocinador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Cpatrocinador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Cinvestimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Cinvestimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnIniciar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CtopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CtopActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // pegando valores dos campos
        
        t1.nomeTime = Cnometime.getText();
        TimeDAO tDAO = new TimeDAO();
        tDAO.inserirTime(t1);
 
        
        Jogador j1 = new Jogador();
        j1.nick = Ctop.getText();
        
        String pesquisa = j1.nick.replaceAll("\\s+","");
        
        Document doc = null;
        try {
            doc = (Document) Jsoup.connect("https://br.op.gg/summoner/userName=" + pesquisa)
                    .timeout(6000).get();
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        Elements rank = doc.select("div.TierRank");
        Elements winr = doc.select("div.TierInfo");
        
        j1.elo = rank.select("div").text();
        j1.winr = winr.select("span.winratio").text();
        j1.win = winr.select("span.wins").text();
        j1.lose = winr.select("span.losses").text();
        
        if (j1.elo.contains("Challenger")) {
            j1.pontuacao = 90;
        }
        else if (j1.elo.contains("Grandmaster")) {
            j1.pontuacao = 80;
        }
        else if (j1.elo.contains("Master")) {
            j1.pontuacao = 70;
        }
        else if (j1.elo.contains("Diamond")) {
            j1.pontuacao = 60;
        }
        else if (j1.elo.contains("Platinum")) {
            j1.pontuacao = 50;
        }
        else if (j1.elo.contains("Gold")) {
            j1.pontuacao = 40;
        }
        else if (j1.elo.contains("Silver")) {
            j1.pontuacao = 30;
        }
        else if (j1.elo.contains("Bronze")) {
            j1.pontuacao = 20;
        }
        else if (j1.elo.contains("Iron")) {
            j1.pontuacao = 10;
        }
        else if (j1.elo.contains("Unranked")) {
            j1.pontuacao = 0;
        }
        
        j1.posicao = jLabel2.getText();
        t1.addIntegrante(j1);
        
        
        Treinador c1 = new Treinador();
        c1.posicao = "Treinador";
        c1.nick = Ctreinador.getText();
        c1.idade = Integer.parseInt(Cidade.getText());
        c1.titulos = Integer.parseInt(Ctitulos.getText());
        if (c1.titulos > 0) {
            c1.pontuacao = 10;
        }else{
            c1.pontuacao = 0;
        }
        t1.addIntegrante(c1);
        t1.calculaPontuacao();
        
        Integrante i1 = new Integrante();
        i1.nick = c1.nick;
        i1.posicao = c1.posicao;
        i1.pontuacao = c1.pontuacao;
        
        IntegranteDAO iDAO = new IntegranteDAO();
        iDAO.inserirIntegrante(i1, t1);
        
        TreinadorDAO cDAO = new TreinadorDAO();
        cDAO.inserirTreinador(c1);
        
        Patrocinador p1 = new Patrocinador();
        p1.investimento = Integer.parseInt(Cinvestimento1.getText());
        p1.marca = Cpatrocinador1.getText();
        t1.addPatrocinio(p1);
        
        PatrocinioDAO pDAO = new PatrocinioDAO();
        pDAO.inserirPatrocinador(p1);
        
        Patrocinador p2 = new Patrocinador();
        p2.investimento = Integer.parseInt(Cinvestimento2.getText());
        p2.marca = Cpatrocinador2.getText();
        t1.addPatrocinio(p2);
        
        pDAO.inserirPatrocinador(p2);
        
        Integrante i2 = new Integrante();
        i2.nick = j1.nick;
        i2.posicao = j1.posicao;
        i2.pontuacao = j1.pontuacao;
        
        
        iDAO.inserirIntegrante(i2, t1);

        JogadorDAO jDAO = new JogadorDAO();
        jDAO.inserirJogador(j1);

        Jogador j2 = new Jogador();
        j2.nick = Cselva.getText();
        
        String pesquisa2 = j2.nick.replaceAll("\\s+","");
        
        try {
            doc = (Document) Jsoup.connect("https://br.op.gg/summoner/userName=" + pesquisa2)
                    .timeout(6000).get();
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        Elements rank2 = doc.select("div.TierRank");
        Elements winr2 = doc.select("div.TierInfo");
        
        j2.elo = rank2.select("div").text();
        j2.winr = winr2.select("span.winratio").text();
        j2.win = winr2.select("span.wins").text();
        j2.lose = winr2.select("span.losses").text();
        
        if (j2.elo.contains("Challenger")) {
            j2.pontuacao = 90;
        }
        else if (j2.elo.contains("Grandmaster")) {
            j2.pontuacao = 80;
        }
        else if (j2.elo.contains("Master")) {
            j2.pontuacao = 70;
        }
        else if (j2.elo.contains("Diamond")) {
            j2.pontuacao = 60;
        }
        else if (j2.elo.contains("Platinum")) {
            j2.pontuacao = 50;
        }
        else if (j2.elo.contains("Gold")) {
            j2.pontuacao = 40;
        }
        else if (j2.elo.contains("Silver")) {
            j2.pontuacao = 30;
        }
        else if (j2.elo.contains("Bronze")) {
            j2.pontuacao = 20;
        }
        else if (j2.elo.contains("Iron")) {
            j2.pontuacao = 10;
        }
        else if (j2.elo.contains("Unranked")) {
            j2.pontuacao = 0;
        }
        
        j2.posicao = jLabel3.getText();
        t1.addIntegrante(j2);
        
        Integrante i3 = new Integrante();
        i3.nick = j2.nick;
        i3.posicao = j2.posicao;
        i3.pontuacao = j2.pontuacao;
        
        
        iDAO.inserirIntegrante(i3, t1);
        
        jDAO.inserirJogador(j2);
        
        Jogador j3 = new Jogador();
        j3.nick = Cmid.getText();
        
        String pesquisa3 = j3.nick.replaceAll("\\s+","");
        
        try {
            doc = (Document) Jsoup.connect("https://br.op.gg/summoner/userName=" + pesquisa3)
                    .timeout(6000).get();
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        Elements rank3 = doc.select("div.TierRank");
        Elements winr3 = doc.select("div.TierInfo");
        
        j3.elo = rank3.select("div").text();
        j3.winr = winr3.select("span.winratio").text();
        j3.win = winr3.select("span.wins").text();
        j3.lose = winr3.select("span.losses").text();
        
        if (j3.elo.contains("Challenger")) {
            j3.pontuacao = 90;
        }
        else if (j3.elo.contains("Grandmaster")) {
            j3.pontuacao = 80;
        }
        else if (j3.elo.contains("Master")) {
            j3.pontuacao = 70;
        }
        else if (j3.elo.contains("Diamond")) {
            j3.pontuacao = 60;
        }
        else if (j3.elo.contains("Platinum")) {
            j3.pontuacao = 50;
        }
        else if (j3.elo.contains("Gold")) {
            j3.pontuacao = 40;
        }
        else if (j3.elo.contains("Silver")) {
            j3.pontuacao = 30;
        }
        else if (j3.elo.contains("Bronze")) {
            j3.pontuacao = 20;
        }
        else if (j3.elo.contains("Iron")) {
            j3.pontuacao = 10;
        }
        else if (j3.elo.contains("Unranked")) {
            j3.pontuacao = 0;
        }
        
        j3.posicao = jLabel4.getText();
        t1.addIntegrante(j3);
        
        Integrante i4 = new Integrante();
        i4.nick = j3.nick;
        i4.posicao = j3.posicao;
        i4.pontuacao = j3.pontuacao;
        
        
        iDAO.inserirIntegrante(i4, t1);
        
        jDAO.inserirJogador(j3);
        
        Jogador j4 = new Jogador();
        j4.nick = Cadc.getText();
        
        String pesquisa4 = j4.nick.replaceAll("\\s+","");
        
        try {
            doc = (Document) Jsoup.connect("https://br.op.gg/summoner/userName=" + pesquisa4)
                    .timeout(6000).get();
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        Elements rank4 = doc.select("div.TierRank");
        Elements winr4 = doc.select("div.TierInfo");
        
        j4.elo = rank4.select("div").text();
        j4.winr = winr4.select("span.winratio").text();
        j4.win = winr4.select("span.wins").text();
        j4.lose = winr4.select("span.losses").text();
        
        if (j4.elo.contains("Challenger")) {
            j4.pontuacao = 90;
        }
        else if (j4.elo.contains("Grandmaster")) {
            j4.pontuacao = 80;
        }
        else if (j4.elo.contains("Master")) {
            j4.pontuacao = 70;
        }
        else if (j4.elo.contains("Diamond")) {
            j4.pontuacao = 60;
        }
        else if (j4.elo.contains("Platinum")) {
            j4.pontuacao = 50;
        }
        else if (j4.elo.contains("Gold")) {
            j4.pontuacao = 40;
        }
        else if (j4.elo.contains("Silver")) {
            j4.pontuacao = 30;
        }
        else if (j4.elo.contains("Bronze")) {
            j4.pontuacao = 20;
        }
        else if (j4.elo.contains("Iron")) {
            j4.pontuacao = 10;
        }
        else if (j4.elo.contains("Unranked")) {
            j4.pontuacao = 0;
        }
        
        j4.posicao = jLabel5.getText();
        t1.addIntegrante(j4);
        
        Integrante i5 = new Integrante();
        i5.nick = j4.nick;
        i5.posicao = j4.posicao;
        i5.pontuacao = j4.pontuacao;
        
        
        iDAO.inserirIntegrante(i5, t1);
        
        jDAO.inserirJogador(j4);

        Jogador j5 = new Jogador();
        j5.nick = Csup.getText();
        
        String pesquisa5 = j5.nick.replaceAll("\\s+","");
        
        try {
            doc = (Document) Jsoup.connect("https://br.op.gg/summoner/userName=" + pesquisa5)
                    .timeout(6000).get();
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        Elements rank5 = doc.select("div.TierRank");
        Elements winr5 = doc.select("div.TierInfo");
        
        j5.elo = rank5.select("div").text();
        j5.winr = winr5.select("span.winratio").text();
        j5.win = winr5.select("span.wins").text();
        j5.lose = winr5.select("span.losses").text();
        
        if (j5.elo.contains("Challenger")) {
            j5.pontuacao = 90;
        }
        else if (j5.elo.contains("Grandmaster")) {
            j5.pontuacao = 80;
        }
        else if (j5.elo.contains("Master")) {
            j5.pontuacao = 70;
        }
        else if (j5.elo.contains("Diamond")) {
            j5.pontuacao = 60;
        }
        else if (j5.elo.contains("Platinum")) {
            j5.pontuacao = 50;
        }
        else if (j5.elo.contains("Gold")) {
            j5.pontuacao = 40;
        }
        else if (j5.elo.contains("Silver")) {
            j5.pontuacao = 30;
        }
        else if (j5.elo.contains("Bronze")) {
            j5.pontuacao = 20;
        }
        else if (j5.elo.contains("Iron")) {
            j5.pontuacao = 10;
        }
        else if (j5.elo.contains("Unranked")) {
            j5.pontuacao = 0;
        }
        
        j5.posicao = jLabel6.getText();
        t1.addIntegrante(j5);
        
        Integrante i6 = new Integrante();
        i6.nick = j5.nick;
        i6.posicao = j5.posicao;
        i6.pontuacao = j5.pontuacao;
        
        
        iDAO.inserirIntegrante(i6, t1);
        
        jDAO.inserirJogador(j5);
      
        JOptionPane.showMessageDialog(this, "Cadastro Realizado");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void CnometimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnometimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnometimeActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        Tela2 tela2 = new Tela2();

        tela2.setVisible(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cadc;
    private javax.swing.JTextField Cidade;
    private javax.swing.JTextField Cinvestimento1;
    private javax.swing.JTextField Cinvestimento2;
    private javax.swing.JTextField Cmid;
    private javax.swing.JTextField Cnometime;
    private javax.swing.JTextField Cpatrocinador1;
    private javax.swing.JTextField Cpatrocinador2;
    private javax.swing.JTextField Cselva;
    private javax.swing.JTextField Csup;
    private javax.swing.JTextField Ctitulos;
    private javax.swing.JTextField Ctop;
    private javax.swing.JTextField Ctreinador;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
